### ISSUE TITLE
Jackson error: Conflicting property name definitions

### ISSUE THREAD

**Issue by unexpected62** [nestlabs/android-sdk#16]
I am finishing up an application and just built and installed the release version of the APK for the first time. Interestingly, it crashes on start. The debug version of the application works fine. I am using proguard in the release version.

The crash occurs once I authenticate with the Nest API. What can I do to get past this? This is a blocker for me releasing my product which is a huge disappointment after 6 months of development.

Here is the stack trace:

`09-06 23:49:31.975 15229-15229/? V/MainActivity: Authentication succeeded.
09-06 23:49:31.977 15229-15229/? V/MainActivity: Registering thermostat listener.
09-06 23:49:31.978 15229-15229/? V/MainActivity: Registering structure listener.
09-06 23:49:31.980 15229-15229/? V/NestService: onCreate()
09-06 23:49:31.981 15229-15229/? V/NestService: onStartCommand()
09-06 23:49:31.981 15229-15229/? D/NestService: Attempting to authenticate
09-06 23:49:32.009 15229-15229/? V/v: Authentication succeeded.
09-06 23:49:32.009 15229-15229/? V/NestService: Registering thermostat listener.
09-06 23:49:32.009 15229-15229/? V/NestService: Registering structure listener.
09-06 23:49:32.807 15229-15229/? D/AndroidRuntime: Shutting down VM
09-06 23:49:32.807 15229-15229/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: <my_package>, PID: 15229
                                                   java.lang.IllegalStateException: Conflicting property name definitions: 'locale' (for [field com.nestlabs.sdk.Device#b]) vs 'name' (for [method com.nestlabs.sdk.Device#b(0 params)])
                                                       at com.fasterxml.jackson.databind.introspect.POJOPropertyBuilder.findRenamed(Unknown Source)
                                                       at com.fasterxml.jackson.databind.introspect.POJOPropertyBuilder.findNewName(Unknown Source)
                                                       at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector._renameProperties(Unknown Source)
                                                       at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.collect(Unknown Source)
                                                       at com.fasterxml.jackson.databind.introspect.BasicClassIntrospector.collectProperties(Unknown Source)
                                                       at com.fasterxml.jackson.databind.introspect.BasicClassIntrospector.forDeserialization(Unknown Source)
                                                       at com.fasterxml.jackson.databind.introspect.BasicClassIntrospector.forDeserialization(Unknown Source)
                                                       at com.fasterxml.jackson.databind.DeserializationConfig.introspect(Unknown Source)
                                                       at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(Unknown Source)
                                                       at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(Unknown Source)
                                                       at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(Unknown Source)
                                                       at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(Unknown Source)
                                                       at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(Unknown Source)
                                                       at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(Unknown Source)
                                                       at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(Unknown Source)
                                                       at com.fasterxml.jackson.databind.ObjectMapper.readValue(Unknown Source)
                                                       at com.firebase.client.d.a(Unknown Source)
                                                       at com.nestlabs.sdk.aa.a(Unknown Source)
                                                       at com.firebase.client.c.ba.run(Unknown Source)
                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

**Comment by unexpected62** [comment]
As suspected, it looks like ProGuard is causing this problem. See a similar issue here: https://github.com/FasterXML/jackson-databind/issues/193

**Comment by unexpected62** [comment]
@ryanseys - as a starting point can we get the Nest SDK to upgrade to Jackson 2.7+? I asked a Jackson expert [here](https://github.com/FasterXML/jackson-databind/issues/193#issuecomment-245401544) and he said 2.6 is not maintained anymore. Maybe the bug will go away with a later version, but if not, then we can have them start looking into it.

**Comment by ryanseys** [comment]
I unfortunately don't have any time to take care of this, as I no longer am the main point of contact for this project. Perhaps @aurman and/or @beriberikix can help? :)

**Comment by unexpected62** [comment]
Thanks for the reply @ryanseys . @aurman and @beriberikix - for context, I do not believe it is possible to create a release APK that uses Proguard while using the Nest Android SDK due to this bug.

**Comment by unexpected62** [comment]
I posted to StackOverflow also: http://stackoverflow.com/questions/39382870/proguard-causing-jackson-error-conflicting-property-name-definitions

**Comment by unexpected62** [comment]
I can reproduce this on the Nest sample SDK app by simply enabling ProGuard, and logging in with my account that I use with Nest Home Simulator. With the sample app, the crash was slightly different, but the same general thing:

```
10-07 00:51:41.726 7308-7308/com.nestlabs.sdk.sample E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       Process: com.nestlabs.sdk.sample, PID: 7308
                                                                       java.lang.IllegalStateException: Conflicting property name definitions: 'locale' (for [field com.nestlabs.sdk.j#b]) vs 'ambient_temperature_f' (for [method com.nestlabs.sdk.ap#b(0 params)])
                                                                           at com.fasterxml.jackson.databind.introspect.POJOPropertyBuilder.findRenamed(Unknown Source)
                                                                           at com.fasterxml.jackson.databind.introspect.POJOPropertyBuilder.findNewName(Unknown Source)
                                                                           at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector._renameProperties(Unknown Source)
                                                                           at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.collect(Unknown Source)
                                                                           at com.fasterxml.jackson.databind.introspect.BasicClassIntrospector.collectProperties(Unknown Source)
                                                                           at com.fasterxml.jackson.databind.introspect.BasicClassIntrospector.forDeserialization(Unknown Source)
                                                                           at com.fasterxml.jackson.databind.introspect.BasicClassIntrospector.forDeserialization(Unknown Source)
                                                                           at com.fasterxml.jackson.databind.DeserializationConfig.introspect(Unknown Source)
                                                                           at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(Unknown Source)
                                                                           at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(Unknown Source)
                                                                           at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(Unknown Source)
                                                                           at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(Unknown Source)
                                                                           at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(Unknown Source)
                                                                           at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(Unknown Source)
                                                                           at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(Unknown Source)
                                                                           at com.fasterxml.jackson.databind.ObjectMapper.readValue(Unknown Source)
                                                                           at com.firebase.client.d.a(Unknown Source)
                                                                           at com.nestlabs.sdk.m.a(Unknown Source)
                                                                           at com.firebase.client.c.ba.run(Unknown Source)
                                                                           at android.os.Handler.handleCallback(Handler.java:739)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                           at android.os.Looper.loop(Looper.java:148)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by harenj** [comment]
@abhishekBansal - did you have this problem? I saw a similar issue you filed in issue #4
