### ISSUE TITLE
Application crash when receiving camera events

### ISSUE THREAD

**Issue by congngale** [nestlabs/android-sdk#20]
I have a problem when listen to Camera event by using Nest library **com.nestlabs:android-sdk:1.1.1**.
My application just crash every time it's received an event of Camera. The error log as below:
`E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                Process: com.veriksystems.venus.manager, PID: 10893
                                                                                com.firebase.client.FirebaseException: Failed to bounce to type
                                                                                    at com.firebase.client.DataSnapshot.getValue(DataSnapshot.java:186)
                                                                                    at com.nestlabs.sdk.CameraValueListener.onDataChange(CameraValueListener.java:45)
                                                                                    at com.firebase.client.core.ValueListenerContainer$1.run(ValueListenerContainer.java:47)
                                                                                    at android.os.Handler.handleCallback(Handler.java:746)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                    at android.os.Looper.loop(Looper.java:148)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5443)
                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
                                                                                 Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "has_person" (class com.nestlabs.sdk.Camera$LastEvent), not marked as ignorable (9 known properties: , "web_url", "has_sound", "start_time", "image_url", "animated_image_url", "app_url", "end_time", "urls_expire_time", "has_motion"])
                                                                                    at [Source: {"is_online":true,"app_url":"nestmobile://cameras/CjZLZUVxQzlQcWNEUk9aZ1RqRTQwZlo5dW5TODk3ZW9RXzhqTVhzQWxsVFBTNGZqNC0td0NGVHcSFkluWUpTdXdVYjR1ak1hMkIzN3dOSUEaNkl0bDQ5R2l6NDBDV2ljNjRmQXJiTWNyQ0hIRnZJWjd0T25Cemd0NHBZZkU1b2ZWSzNQTURiUQ?auth=c.VQdF7xFDkhygyAzqBkfNiAyPVa20miWjPIHvEcCoLxPB4AQxjBCCuRMHZPELqfMgG75PY45np6RxfgzQz8FUWR9FEGNmcwSNAUWI6bd0IYXWIGHahoAeHCx35yA6Sd9boOUKooqrBWtyQmxO","web_url":"https://home.nest.com/cameras/CjZLZUVxQzlQcWNEUk9aZ1RqRTQwZlo5dW5TODk3ZW9RXzhqTVhzQWxsVFBTNGZqNC0td0NGVHcSFkluWUpTdXdVYjR0Tko0VEZLLV9HcVEaNkl0bDQ5R2l6NDBDV2ljNjRmQXJiTWNyQ0hIRnZJWjd0T25Cemd0NHBZZkU1b2ZWSzNQTURiUQ?auth=c.VQdF7xFDkhygyAzqBkfNiAyPVa20miWjPIHvEcCoLxPB4AQxjBCCuRMHZPELqfMgG75PY45np6RxfgzQz8FUWR9FEGNmcwSNAUWI6bd0IYXWIGHahoAeHCx35yA6Sd9boOUKooqrBWtyQmxO","last_is_online_change":"2016-11-30T11:26:42.000Z","device_id":"KeEqC9PqcDROZgTjE40fZ9unS897eoQ_8jMXsAllTPS4fj4--wCFTw","last_event":{"end_time":"2016-12-01T02:57:59.521Z","has_motion":true,"has_person":true,"start_time":"2016-12-01T02:57:39.120Z","app_url":"nestmobile://cameras/CjZLZUVxQzlQcWNEUk9aZ1RqRTQwZlo5dW5TODk3ZW9RXzhqTVhzQWxsVFBTNGZqNC0td0NGVHcSFkluWUpTdXdVYjR1ak1hMkIzN3dOSUEaNkl0bDQ5R2l6NDBDV2ljNjRmQXJiTWNyQ0hIRnZJWjd0T25Cemd0NHBZZkU1b2ZWSzNQTURiUQ/cuepoints/InYJSuwUb4swiXuxiqOufA?auth=c.VQdF7xFDkhygyAzqBkfNiAyPVa20miWjPIHvEcCoLxPB4AQxjBCCuRMHZPELqfMgG75PY45np6RxfgzQz8FUWR9FEGNmcwSNAUWI6bd0IYXWIGHahoAeHCx35yA6Sd9boOUKooqrBWtyQmxO","web_url":"https://home.nest.com/cameras/CjZLZUVxQzlQcWNEUk9aZ1RqRTQwZlo5dW5TODk3ZW9RXzhqTVhzQWxsVFBTNGZqNC0td0NGVHcSFkluWUpTdXdVYjR1ak1hMkIzN3dOSUEaNkl0bDQ5R2l6NDBDV2ljNjRmQXJiTWNyQ0hIRnZJWjd0T25Cemd0NHBZZkU1b2ZWSzNQTURiUQ/cuepoints/InYJSuwUb4swiXuxiqOufA?auth=c.VQdF7xFDkhygyAzqBkfNiAyPVa20miWjPIHvEcCoLxPB4AQxjBCCuRMHZPELqfMgG75PY45np6RxfgzQz8FUWR9FEGNmcwSNAUWI6bd0IYXWIGHahoAeHCx35yA6Sd9boOUKooqrBWtyQmxO","urls_expire_time":"2016-12-11T02:57:39.120Z","has_sound":false},"name":"Family Room","structure_id":"H43Cj_A-3dcPQS_BMD13KGIGGE6Yq3kXb73EdVsKBQZhDkhPaiFzWA","where_id":"wfXilMbONlkwHD2kAqyAffufC4CXpwoi7X6pPzeZ-fOQY6RwE762xg","software_version":"205-600052","name_long":"Family Room Camera","is_streaming":true,"is_video_history_enabled":true,"is_audio_input_enabled":true}; line: 1, column: 971] (through reference chain: com.nestlabs.sdk.Camera["last_event"]->com.nestlabs.sdk.LastEvent["has_person"])
                                                                                    at com.fasterxml.jackson.databind.DeserializationContext.reportUnknownProperty(DeserializationContext.java:555)
                                                                                    at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:708)
                                                                                    at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1160)
                                                                                    at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:315)
                                                                                    at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:121)
                                                                                	at com.fasterxml.jackson.databind.deser.SettableB`

**Comment by dudepants** [comment]
This is related to the previous issue of the missing "has_person" field in the inner class of LastEvent in Camera.

**Comment by congngale** [comment]
It has been fixed and merged into master.
