### ISSUE TITLE
Sample app can't login.

### ISSUE THREAD

**Issue by tmshih** [nestlabs/android-sdk#27]
Login nest user and come with exception reports as following:

com.nestlabs.sdk.sample E/NestAuthActivity: Failed to parse response for token.
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "user_id" (class com.nestlabs.sdk.NestToken), not marked as ignorable (2 known properties: , "expires_in", "access_token"])

**Comment by Steve-MyLiveGuard** [comment]
Hi, afraid I'm experiencing the same issue.  I have implemented a dirty fix for now from [stackoverflow](http://stackoverflow.com/a/25718495) if that helps anyone in the meantime.

Has the structure of NestToken.java changed by any chance?

**Comment by tmshih** [comment]
Hi! Steve!

As workaround of mine:
1. I cloned NestToken as NestTokenYoYo, and expand the field 'user_id'.
2. Designing a method to create NestToken instance, by using constructor NestToken(String token, long expiresIn).
3. Catching the nest token in com.nestlabs.sdk.NestAuthActivity:
NestTokenYoYo tokenYoYo = OBJECT_MAPPER.readValue(body, NestTokenYoYo.class);
NestToken nestToken = tokenYoYo.createNestToken();

**Comment by tmshih** [comment]
Unfortunately, I think the answer is no if we still want to use Nest API by:
compile 'com.nestlabs:android-sdk:1.1.1'

**Comment by harenj** [comment]
I am seeing this in my app [ThermoStats](https://play.google.com/store/apps/details?id=com.jaredharen.harvest) which is live on the Play Store. New users that download my app are unable to log in.

```
03-29 11:00:56.048 20508-20762/? E/NestAuthActivity: Failed to parse response for token.
                                                     com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "user_id" (class com.nestlabs.sdk.NestToken), not marked as ignorable (2 known properties: , "expires_in", "access_token"])
                                                         at [Source: {"access_token":"<redacted>","expires_in":315360000,"user_id":"3286882"}; line: 1, column: 200] (through reference chain: com.nestlabs.sdk.NestToken["user_id"])
                                                         at com.fasterxml.jackson.databind.DeserializationContext.reportUnknownProperty(DeserializationContext.java:555)
                                                         at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:708)
                                                         at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1160)
                                                         at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:315)
                                                         at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:121)
                                                         at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2888)
                                                         at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2034)
                                                         at com.nestlabs.sdk.NestAuthActivity$RedirectClient$1.onResponse(NestAuthActivity.java:165)
                                                         at okhttp3.RealCall$AsyncCall.execute(RealCall.java:133)
                                                         at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:33)
                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                         at java.lang.Thread.run(Thread.java:818)
```

**Comment by harenj** [comment]
I sent this to the affected users:

>>>
Hi ThermoStats users,

If you have had problems logging in to the ThermoStats app recently, you are not alone!

I have just received a message from a representative at Nest who confirmed there is a problem due to a new field that was added on their servers. He estimated that they will have a release to remove this field which caused the problem by next week, but he did not have a solid date. I will reach out again when I have more information.

Thank you for your patience. My apologies for this inconvenience.

Jared Haren
>>>

**Comment by aurman** [comment]
Huge apologies on the lack of communication here. There was a regression that added an extra value to the token response. The extra value broke the parser on the SDK which caused this issue. As of yesterday we pushed a release to remove the user_id from the token response which should fix this issue.

**Comment by harenj** [comment]
@tmshih can you check if the issue is resolved for you? As @aurman said, I think the issue is fixed. My users that were having problems confirmed they can now log in.

**Comment by tmshih** [comment]
It works! Thanks a lot!
@aurman @harenj
