### ISSUE TITLE
Implementing authorization doesn't return token to activity

### ISSUE THREAD

**Issue by jgthibodeau** [nestlabs/android-sdk#3]
Implementing nest authorization:
When the webview is shown for the Nest agreement the following warnings are present:
```
[INFO:CONSOLE(202)] "WARNING: The 'bindAttr' view helper is deprecated in favor of 'bind-attr'", source: https://home.nest.com/js/login/main-5868c8fd.js (202)
[INFO:CONSOLE(202)] "WARNING: The 'bindAttr' view helper is deprecated in favor of 'bind-attr'", source: https://home.nest.com/js/login/main-5868c8fd.js (202)
```
After clicking accept/logging in the following deprecation message is sent:
```
"DEPRECATION: Action handlers implemented directly on controllers are deprecated in favor of action handlers on an `actions` object ( action: `didContinue` on <.LoginController:ember305>)
at Ember.ControllerMixin.Ember.Mixin.create.deprecatedSend (https://home.nest.com/js/login/main-5868c8fd.js:304:584)
at Ember.ActionHandler.Ember.Mixin.create.send (https://home.nest.com/js/login/main-5868c8fd.js:288:521)
at https://home.nest.com/js/login/main-5868c8fd.js:435:415
at Object.n.run (https://home.nest.com/js/login/main-5868c8fd.js:218:981)
at Object.Ember.run (https://home.nest.com/js/login/main-5868c8fd.js:222:15)
at Object.u.registeredActions.(anonymous function).handler (https://home.nest.com/js/login/main-5868c8fd.js:435:383)
at HTMLInputElement.<anonymous> (https://home.nest.com/js/login/main-5868c8fd.js:316:361)
at Object.Ember.handleErrors (https://home.nest.com/js/login/main-5868c8fd.js:186:321)
at HTMLInputElement.<anonymous> (https://home.nest.com/js/login/main-5868c8fd.js:316:199)", source: https://home.nest.com/js/login/main-5868c8fd.js (202)
```
After this, the webview shows the token as the regular webpage would, but it stays on this page and does not return control to the activity. If the webview is closed via the back button, the authWorkFlow activity returns canceled and the token is not returned.

I haven't looked at the code within NestAPI.launchAuthWorkFlow, but it seems to be a problem with the Nest authorization webpage's javascript and how the API expects to handle it.

This also occurs with the sample android app here https://github.com/nestlabs/android-sdk-sample the only changes being to set constants appropriately.

**Comment by jgthibodeau** [comment]
Solved, problem was unclear directions for setup.
Setting "https://redirect-url" to "http://localhost/" in nest.setConfig("client-id", "client-secret", "https://redirect-url"); allows the authWorkFlow to return correctly.
