### ISSUE TITLE
Crash when proguard is enabled

### ISSUE THREAD

**Issue by abhishekBansal** [nestlabs/android-sdk#4]
I am getting a crash with following callstack when proguard is enabled in my app
```
java.lang.NoSuchFieldError
                                                     at libcore.reflect.AnnotationAccess.decodeValue(AnnotationAccess.java:688)
                                                     at libcore.reflect.AnnotationAccess.toAnnotationInstance(AnnotationAccess.java:663)
                                                     at libcore.reflect.AnnotationAccess.toAnnotationInstance(AnnotationAccess.java:641)
                                                     at libcore.reflect.AnnotationAccess.getDeclaredAnnotation(AnnotationAccess.java:170)
                                                     at libcore.reflect.AnnotationAccess.getAnnotation(AnnotationAccess.java:72)
                                                     at java.lang.Class.getAnnotation(Class.java:343)
                                                     at com.b.a.c.f.ae.<clinit>(Unknown Source)
                                                     at com.b.a.c.f.ae.a(Unknown Source)
                                                     at com.b.a.c.z.<clinit>(Unknown Source)
                                                     at com.c.a.j.<clinit>(Unknown Source)
                                                     at com.nestlabs.sdk.NestAPI.setAndroidContext(Unknown Source)
                                                     at com.myapp.android.more.NestControlFragment.a(Unknown Source)
                                                     at android.support.v4.b.p.b(Unknown Source)
                                                     at android.support.v4.b.ad.a(Unknown Source)
                                                     at android.support.v4.b.ad.a(Unknown Source)
                                                     at android.support.v4.b.e.run(Unknown Source)
                                                     at android.support.v4.b.ad.f(Unknown Source)
                                                     at android.support.v4.b.ad.b(Unknown Source)
                                                     at android.support.v4.b.aq.b(Unknown Source)
                                                     at android.support.v4.view.ViewPager.a(Unknown Source)
                                                     at android.support.v4.view.ViewPager.c(Unknown Source)
                                                     at android.support.v4.view.ViewPager.onMeasure(Unknown Source)
                                                     at android.view.View.measure(View.java:17448)
                                                     at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:727)
                                                     at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:463)
                                                     at android.view.View.measure(View.java:17448)
                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5465)
                                                     at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
                                                     at android.view.View.measure(View.java:17448)
                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5465)
                                                     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
                                                     at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
                                                     at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
                                                     at android.view.View.measure(View.java:17448)
                                                     at android.support.v4.widget.DrawerLayout.onMeasure(Unknown Source)
                                                     at android.view.View.measure(View.java:17448)
                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5465)
                                                     at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
                                                     at android.view.View.measure(View.java:17448)
                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5465)
                                                     at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
                                                     at android.support.v7.widget.ContentFrameLayout.onMeasure(Unknown Source)
                                                     at android.view.View.measure(View.java:17448)
                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5465)
                                                     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
                                                     at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
                                                     at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
                                                     at android.view.View.measure(View.java:17448)
                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5465)
                                                     at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
                                                     at android.view.View.measure(View.java:17448)
                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5465)
                                                     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
                                                     at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
                                                     at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
                                                     at android.view.View.measure(View.java:17448)
                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5465)
                                                     at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
                                                     at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2560)
                                                     at android.view.View.measure(View.java:17448)
                                                     at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2031)
                                                     at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1189)
                                                     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1402)
                                                 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl
```

I have tried putting following in proguard-rules.pro file but of no use
```
-keep class com.nestlabs.sdk.** {*;}
-keepnames class com.nestlabs.sdk.** { *; }
-keepattributes *Annotation*,EnclosingMethod
```

**Comment by abhishekBansal** [comment]
Adding following lines to project do the trick

```
-keepclasseswithmembers class com.nestlabs.sdk.** { *; }
-keepclasseswithmembers class com.firebase.** { *; }
-keepclasseswithmembers class com.fasterxml.jackson.** { *; }
```
